import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import {
  createStyles,
  Flex,
  Grid,
  Group,
  Paper,
  Text,
  Avatar,
  Input,
  Stack
} from '@mantine/core';
import { AddFeed } from '@/Components/AddFeed';
import { TrendingPosts } from '@/Components/TrendingPosts';
import { Events } from '@/Components/Events';
import DefaultLayout from '@/Components/DefaultLayout';
import { SingleEvent } from '@/Components/SingleEvent';
import { Feed } from "@/Components/Feed";
import { UserInfo } from "@/Components/UserInfo";

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <DefaultLayout>
      <Head>
        <title>TW / user 123</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <UserInfo />

      <Stack mt="md" >
        <Feed />
        <Feed />
        <Feed />
      </Stack>
    </DefaultLayout>
  );
}
