import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import {
  createStyles,
  Flex,
  Grid,
  Group,
  Paper,
  Text,
  Avatar,
  Input,
} from '@mantine/core';
import { AddFeed } from '@/Components/AddFeed';
import { TrendingPosts } from '@/Components/TrendingPosts';
import { Events } from '@/Components/Events';
import DefaultLayout from '@/Components/DefaultLayout';
import { SingleEvent } from '@/Components/SingleEvent';
import { TrendingEvents } from '@/Components/PopularEvents';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <DefaultLayout
      Right={() => <TrendingEvents />}
      Left={() => <TrendingPosts />}
    >
      <Head>
        <title>Very Usefull APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SingleEvent />
    </DefaultLayout>
  );
}
