import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import {
  createStyles,
  Flex,
  Grid,
  Group,
  Paper,
  Text,
  Avatar,
  Input,
  Stack,
} from "@mantine/core";
import { AddFeed } from "@/Components/AddFeed";
import { Feed } from "@/Components/Feed";
import { TrendingPosts } from "@/Components/TrendingPosts";
import { Events } from "@/Components/Events";
import DefaultLayout from "@/Components/DefaultLayout";
import { useQuery } from "@tanstack/react-query";
import APIService from "@/api";
import { IPost } from "@/sharedInterfaces/post";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const postQuery = useQuery({
    queryKey: ["allPosts"],
    queryFn: APIService.getAllPosts,
    initialData: [],
  });

  return (
    <DefaultLayout Left={() => <TrendingPosts />} Right={() => <Events />}>
      <Head>
        <title>Very Usefull APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AddFeed />

      <Stack mt="md">
        {postQuery.data.map((post: IPost) => (
          <Feed key={post.id} data={post} />
        ))}
      </Stack>
    </DefaultLayout>
  );
}
